name: Deploy Spring Boot to EC2

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Build with Maven
        run: mvn clean package

      - name: Decode SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" | base64 -d > key.pem
          chmod 600 key.pem

      - name: Copy JAR to EC2
        run: |
          scp -i key.pem -o StrictHostKeyChecking=no target/task-manager-0.0.1-SNAPSHOT.jar ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/

      - name: Deploy and restart app on EC2
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
            if ! command -v java >/dev/null 2>&1; then
              if [ -f /etc/os-release ] && grep -q "Amazon Linux" /etc/os-release; then
                if grep -q "2023" /etc/os-release; then
                  sudo dnf install java-17-amazon-corretto -y
                else
                  sudo yum install java-17-openjdk -y
                fi
              elif [ -f /etc/os-release ] && grep -q "Ubuntu" /etc/os-release; then
                sudo apt update
                sudo apt install openjdk-17-jdk -y
              else
                echo "Unsupported OS. Please install Java manually."
                exit 1
              fi
            fi
            export DB_HOST="${DB_HOST}"
            export DB_NAME="${DB_NAME}"
            export DB_USER="${DB_USER}"
            export DB_PASSWORD="${DB_PASSWORD}"
            pkill -f "java -jar" || true
            nohup java -jar ~/task-manager-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod > app.log 2>&1 &
          '
